apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  labels:
    {{- include "gateways.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - argocd.{{ .Values.domain }}
    secretName: argocd-tls
  rules:
   - host: argocd.{{ .Values.domain }}
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: argocd-server.argocd.svc.cluster.local
                port: 
                  number: 80
