kind: Service
apiVersion: v1
metadata:
  name: argocd-service-externalname
  labels:
    {{- include "gateways.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  labels:
    {{- include "gateways.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - argocd.{{ .Values.domain }}
    secretName: argocd-cert
  rules:
   - host: argocd.{{ .Values.domain }}
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: argocd-service-externalname
                port: 
                  number: 80
