apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: test-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    path: k8s/charts/test-app/
    repoURL: https://github.com/bakavetsbiz/demo-dsd.git
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        hosts:
          app-1: app-1.devops-lab.co.uk
          app-2: app-1.devops-lab.co.uk

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
